# Generated by Django 5.2.15 on 2026-06-21 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('publisher', models.CharField(default='DU', max_length=16)),
                ('year', models.IntegerField()),
                ('position', models.IntegerField()),
                ('citation_suffix', models.CharField(max_length=128)),
                ('eli_id', models.CharField(blank=True, max_length=64)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Akt',
                'verbose_name_plural': 'Akty',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualificationQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('ulgi', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Qualification queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=16)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ulgi.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('running', 'W toku'), ('success', 'Sukces'), ('failed', 'Błąd')], default='pending', max_length=16)),
                ('obowiazuje_od', models.DateField(blank=True, null=True)),
                ('chunks_indexed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('akt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ulgi.akt')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opensearch_id', models.CharField(max_length=64, unique=True)),
                ('article_num', models.CharField(max_length=16)),
                ('ustep', models.CharField(blank=True, max_length=16)),
                ('citation', models.CharField(max_length=256)),
                ('ulga', models.CharField(blank=True, choices=[('BR', 'Ulga B+R'), ('IPBOX', 'IP Box'), ('PKUP', 'Koszty autorskie'), ('', '—')], max_length=16)),
                ('source_type', models.CharField(choices=[('ustawa', 'Ustawa'), ('objasnienia', 'Objaśnienia MF'), ('interpretacja', 'Interpretacja'), ('orzeczenie', 'Orzeczenie')], default='ustawa', max_length=24)),
                ('content_text', models.TextField()),
                ('eli_id', models.CharField(blank=True, max_length=64)),
                ('obowiazuje_od', models.DateField(blank=True, null=True)),
                ('obowiazuje_do', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ulgi.akt')),
            ],
            options={
                'ordering': ['akt', 'article_num', 'ustep'],
                'indexes': [models.Index(fields=['ulga'], name='ulgi_chunk_ulga_057332_idx'), models.Index(fields=['source_type'], name='ulgi_chunk_source__a3c489_idx'), models.Index(fields=['article_num'], name='ulgi_chunk_article_2ea0aa_idx')],
            },
        ),
    ]
