# Generated by Django 5.2.15 on 2026-06-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulgi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akt',
            name='nowele',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='akt',
            name='nowele_po_tj',
            field=models.IntegerField(default=0),
        ),
    ]
