# Generated by Django 5.2.15 on 2026-06-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulgi', '0002_akt_nowele_akt_nowele_po_tj'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
